---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.namespace }}-service"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.namespace }}
    component: mpva
spec:
  type: NodePort
  ports:
    - port: {{ .Values.server.port }}
      targetPort: rest
      protocol: TCP
      name: rest
  selector:
    app: {{ .Values.namespace }}
